### ISSUE TITLE
Introducing Educational plan Better Code Hub at University of Bristol?

### ISSUE THREAD

**Issue by MichielCuijpers** [harrymt/HarrysChatServer#1]
Hi Harry

Thanks for using bettercodehub.com for analyzing code quality. 
Did you know we have a free plan for Education? This is about free access for analyzing private repos too.  For your reference: https://education.github.community/t/a-proposed-add-on-for-code-quality-in-software-engineering-courses-using-github/9067/4
Could you connect me with your Professor Software Engineering that is tasked with code metrics & use of Github, please?

Best Regards Michiel

**Comment by harrymt** [comment]
Hey @MichielCuijpers,

Thank you for reaching out, I am always interested in improving code quality.

For University engagement, please could you contact the University Computer Science department directly (mvse-cshod@bristol.ac.uk)

See more:
http://www.bristol.ac.uk/engineering/departments/computerscience/contact/ 

Thanks,
Harry
